title: "NSS TEAM"
date: 2020-03-26
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
[Как нас процитировать](https://github.com/ITMO-NSS-team/FEDOT.Algs/wiki/%D0%9A%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81-%D0%BF%D1%80%D0%BE%D1%86%D0%B8%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C)
[Руководство по работе с репозиторием](https://github.com/ITMO-NSS-team/FEDOT.Algs/wiki/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D0%BF%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5-%D1%81-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B5%D0%BC)
[Фреймворк FEDOT](https://github.com/ITMO-NSS-team/FEDOT.Algs/wiki/%D0%A4%D1%80%D0%B5%D0%B9%D0%BC%D0%B2%D0%BE%D1%80%D0%BA-FEDOT)
[Автоматическое машинное обучение](https://github.com/ITMO-NSS-team/FEDOT.Algs/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)
[How to embed custom model into the FEDOT pipeline](https://github.com/ITMO-NSS-team/FEDOT.Algs/wiki/How-to-embed-custom-model-into-the-Fedot-pipeline)
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

