title: "NSS TEAM"
date: 2020-03-26
theme: jekyll-theme-tactile
description: > # this means to ignore newlines until "baseurl:"
  Our team is part of eScience Research Institute (ITMO University, Russia), which provides cutting-edge knowledge-intensive software and solutions. We focus on natural systems simulations, modelling and optimization tasks. Our research (examples are below) will be useful in forecasting and preventing of natural disasters, accident consequences management, rescue operations, risk-assessment and other tasks.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

